### ISSUE TITLE
Milestones: CATALOG - Code Review 1

### ISSUE THREAD

**Issue by dakotafabro** [2206-GHP-HEX-GIRLS/hex-girls-grace-shopper#37]
- [x] Customers can browse & filter by category
- [x] Admins can add & edit products

EC:
- [x] 🌟Customers can do full text search on the catalog
- [ ] 🌟Catalog is paginated
