### ISSUE TITLE
Milestones: CART - Code Review 2

### ISSUE THREAD

**Issue by dakotafabro** [2206-GHP-HEX-GIRLS/hex-girls-grace-shopper#38]
- [ ] Customers have a cart they can put stuff in while they shop
- [ ] Customers can see their order history

EC:
- [ ] 🌟Customers always have their cart, on any device
