### ISSUE TITLE
Milestones: CHECKOUT - During Presentation

### ISSUE THREAD

**Issue by dakotafabro** [2206-GHP-HEX-GIRLS/hex-girls-grace-shopper#39]
- [ ] Customers can checkout, using a real payment api (probably Stripe)
- [ ] Admins can see pending orders that need to be shipped

EC:
- [ ] 🌟Customers get email confirmations
